### ISSUE TITLE
error in file(con, "r"): cannot open the connection to GWS

### ISSUE THREAD

**Issue by PaulineGnsr** [adamkocsis/rgplates#1]
Hi Adam,

I am used with rgplates and it has worked very well until last week. I am having two different issues (the second in another report) about reconstructing paleocoordinates and paleomapping. 
Below the R script I use and the error message:

> plOff100 <- rgplates::reconstruct("coastlines", age=505, model="PALEOMAP")
Erreur dans file(con, "r") : impossible d'ouvrir la connexion vers 'https://gws.gplates.org/reconstruct/coastlines/?time=100.000000&model=PALEOMAP&anchor_plate_id=0'
De plus : Message d'avis :
Dans file(con, "r") : URL ‘https://gws.gplates.org/reconstruct/coastlines/?time=100.000000&model=PALEOMAP&anchor_plate_id=0’: délais maximal de 60 secondes atteint

In English, it would say (sorry for the original French text): 
"error in file(con, "r"): cannot open the connection to [...]"
"Moreover, notification: in file(con, "r"): URL [...]: maximum delay of 60 seconds reached"

Is it a temporal bug?
Thank you for your help,
Pauline Guenser

**Comment by adamkocsis** [comment]
Hi Pauline, I think it is - it seems that the GPlates Web Service is currently not accessible. We have started the discussions on creating backups for such cases - but there is none yet. I hope that it will be brought back online soon.

**Comment by adamkocsis** [comment]
A backup instance for the GWS is planned to be instantiated for the next year. In the meantime rgplates v0.4.1 allows connection to a [locally running instance of the GWS](https://gplates.github.io/rgplates/), using the new `setgws()` function.
