### ISSUE TITLE
Error in winDefaultGPlates() : Could not locate GPlates.

### ISSUE THREAD

**Issue by PaulineGnsr** [adamkocsis/rgplates#2]
Hi Adam,

I am used with rgplates and it has worked very well until last week. I am having two different issues (already submit a first issue) about reconstructing paleocoordinates and offline paleomapping.

I followed the tutorial available here: https://adamtkocsis.com/rgplates/articles/4_offline_reconstruction.html
Below the R script I use and the error message:

> td <- tempdir()
> rgPath <- system.file(package="rgplates")
> unzip(file.path(rgPath,"extdata/paleomap_v3.zip"), exdir=td)
> pathToPolygons <- file.path(td, "PALEOMAP_PlatePolygons.gpml")
> pathToRotations <- file.path(td, "PALEOMAP_PlateModel.rot")
> pm <- platemodel(features=c("static_polygons"=pathToPolygons), rotation=pathToRotations)
> plOff100 <- rgplates::reconstruct("static_polygons", age=100, model=pm)

**Erreur dans winDefaultGPlates() : Could not locate GPlates.**

Thank you for your help,
Pauline Guenser

**Comment by adamkocsis** [comment]
Do you have the [GPlates Desktop Application ](https://www.earthbyte.org/download-gplates-2-5/)installed? If it is installed, did you install it somewhere else than the default?
